<?php
/** @package Franchise::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CompanyMap.php");

/**
 * CompanyDAO provides object-oriented access to the company table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Franchise::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CompanyDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Name;

	/** @var string */
	public $Code;

	/** @var string */
	public $Territory;

	/** @var string */
	public $Region;

	/** @var date */
	public $Start;

	/** @var string */
	public $Phone;

	/** @var string */
	public $Mobile;

	/** @var string */
	public $Email;

	/** @var string */
	public $Address;

	/** @var string */
	public $Suburb;

	/** @var string */
	public $Postcode;

	/** @var string */
	public $State;

	/** @var string */
	public $City;

	/** @var timestamp */
	public $CreatedDate;

	/** @var timestamp */
	public $UpdatedDate;

	/** @var int */
	public $Status;



}
?>