<?php
/** @package Franchise::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ScheduleMap.php");

/**
 * ScheduleDAO provides object-oriented access to the schedule table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Franchise::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ScheduleDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $WorkId;

	/** @var int */
	public $AccountId;

	/** @var date */
	public $Startdate;

	/** @var date */
	public $Enddate;

	/** @var int */
	public $Maximum;

	/** @var timestamp */
	public $CreatedDate;

	/** @var timestamp */
	public $UpdatedDate;

	/** @var int */
	public $Status;



}
?>